# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator_interface_copy.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(370, 407)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 361, 351))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.BUTTON_ENTER = QtWidgets.QPushButton(self.frame)
        self.BUTTON_ENTER.setGeometry(QtCore.QRect(0, 300, 91, 51))
        self.BUTTON_ENTER.setMinimumSize(QtCore.QSize(91, 51))
        self.BUTTON_ENTER.setMaximumSize(QtCore.QSize(91, 51))
        self.BUTTON_ENTER.setObjectName("BUTTON_ENTER")
        self.BUTTON_CLEAR = QtWidgets.QPushButton(self.frame)
        self.BUTTON_CLEAR.setGeometry(QtCore.QRect(90, 300, 91, 51))
        self.BUTTON_CLEAR.setMinimumSize(QtCore.QSize(91, 51))
        self.BUTTON_CLEAR.setMaximumSize(QtCore.QSize(91, 51))
        self.BUTTON_CLEAR.setObjectName("BUTTON_CLEAR")
        self.BUTTON_PERIOD = QtWidgets.QPushButton(self.frame)
        self.BUTTON_PERIOD.setGeometry(QtCore.QRect(180, 300, 91, 51))
        self.BUTTON_PERIOD.setMinimumSize(QtCore.QSize(91, 51))
        self.BUTTON_PERIOD.setMaximumSize(QtCore.QSize(91, 51))
        self.BUTTON_PERIOD.setObjectName("BUTTON_PERIOD")
        self.BUTTON_STORE = QtWidgets.QPushButton(self.frame)
        self.BUTTON_STORE.setGeometry(QtCore.QRect(270, 300, 91, 51))
        self.BUTTON_STORE.setMinimumSize(QtCore.QSize(91, 51))
        self.BUTTON_STORE.setMaximumSize(QtCore.QSize(91, 51))
        self.BUTTON_STORE.setObjectName("BUTTON_STORE")
        self.BUTTON_TWO = QtWidgets.QPushButton(self.frame)
        self.BUTTON_TWO.setGeometry(QtCore.QRect(180, 250, 91, 51))
        self.BUTTON_TWO.setMinimumSize(QtCore.QSize(91, 51))
        self.BUTTON_TWO.setMaximumSize(QtCore.QSize(91, 51))
        self.BUTTON_TWO.setObjectName("BUTTON_TWO")
        self.BUTTON_PLUS = QtWidgets.QPushButton(self.frame)
        self.BUTTON_PLUS.setGeometry(QtCore.QRect(270, 250, 91, 51))
        self.BUTTON_PLUS.setMinimumSize(QtCore.QSize(91, 51))
        self.BUTTON_PLUS.setMaximumSize(QtCore.QSize(91, 51))
        self.BUTTON_PLUS.setObjectName("BUTTON_PLUS")
        self.BUTTON_ZERO = QtWidgets.QPushButton(self.frame)
        self.BUTTON_ZERO.setGeometry(QtCore.QRect(0, 250, 91, 51))
        self.BUTTON_ZERO.setMinimumSize(QtCore.QSize(91, 51))
        self.BUTTON_ZERO.setMaximumSize(QtCore.QSize(91, 51))
        self.BUTTON_ZERO.setObjectName("BUTTON_ZERO")
        self.BUTTON_ONE = QtWidgets.QPushButton(self.frame)
        self.BUTTON_ONE.setGeometry(QtCore.QRect(90, 250, 91, 51))
        self.BUTTON_ONE.setMinimumSize(QtCore.QSize(91, 51))
        self.BUTTON_ONE.setMaximumSize(QtCore.QSize(91, 51))
        self.BUTTON_ONE.setObjectName("BUTTON_ONE")
        self.BUTTON_FIVE = QtWidgets.QPushButton(self.frame)
        self.BUTTON_FIVE.setGeometry(QtCore.QRect(180, 200, 91, 51))
        self.BUTTON_FIVE.setMinimumSize(QtCore.QSize(91, 51))
        self.BUTTON_FIVE.setMaximumSize(QtCore.QSize(91, 51))
        self.BUTTON_FIVE.setObjectName("BUTTON_FIVE")
        self.BUTTON_MINUS = QtWidgets.QPushButton(self.frame)
        self.BUTTON_MINUS.setGeometry(QtCore.QRect(270, 200, 91, 51))
        self.BUTTON_MINUS.setMinimumSize(QtCore.QSize(91, 51))
        self.BUTTON_MINUS.setMaximumSize(QtCore.QSize(91, 51))
        self.BUTTON_MINUS.setObjectName("BUTTON_MINUS")
        self.BUTTON_THREE = QtWidgets.QPushButton(self.frame)
        self.BUTTON_THREE.setGeometry(QtCore.QRect(0, 200, 91, 51))
        self.BUTTON_THREE.setMinimumSize(QtCore.QSize(91, 51))
        self.BUTTON_THREE.setMaximumSize(QtCore.QSize(91, 51))
        self.BUTTON_THREE.setObjectName("BUTTON_THREE")
        self.BUTTON_FOUR = QtWidgets.QPushButton(self.frame)
        self.BUTTON_FOUR.setGeometry(QtCore.QRect(90, 200, 91, 51))
        self.BUTTON_FOUR.setMinimumSize(QtCore.QSize(91, 51))
        self.BUTTON_FOUR.setMaximumSize(QtCore.QSize(91, 51))
        self.BUTTON_FOUR.setObjectName("BUTTON_FOUR")
        self.BUTTON_EIGHT = QtWidgets.QPushButton(self.frame)
        self.BUTTON_EIGHT.setGeometry(QtCore.QRect(180, 150, 91, 51))
        self.BUTTON_EIGHT.setMinimumSize(QtCore.QSize(91, 51))
        self.BUTTON_EIGHT.setMaximumSize(QtCore.QSize(91, 51))
        self.BUTTON_EIGHT.setObjectName("BUTTON_EIGHT")
        self.BUTTON_MULT = QtWidgets.QPushButton(self.frame)
        self.BUTTON_MULT.setGeometry(QtCore.QRect(270, 150, 91, 51))
        self.BUTTON_MULT.setMinimumSize(QtCore.QSize(91, 51))
        self.BUTTON_MULT.setMaximumSize(QtCore.QSize(91, 51))
        self.BUTTON_MULT.setObjectName("BUTTON_MULT")
        self.BUTTON_SIX = QtWidgets.QPushButton(self.frame)
        self.BUTTON_SIX.setGeometry(QtCore.QRect(0, 150, 91, 51))
        self.BUTTON_SIX.setMinimumSize(QtCore.QSize(91, 51))
        self.BUTTON_SIX.setMaximumSize(QtCore.QSize(91, 51))
        self.BUTTON_SIX.setObjectName("BUTTON_SIX")
        self.BUTTON_SEVEN = QtWidgets.QPushButton(self.frame)
        self.BUTTON_SEVEN.setGeometry(QtCore.QRect(90, 150, 91, 51))
        self.BUTTON_SEVEN.setMinimumSize(QtCore.QSize(91, 51))
        self.BUTTON_SEVEN.setMaximumSize(QtCore.QSize(91, 51))
        self.BUTTON_SEVEN.setObjectName("BUTTON_SEVEN")
        self.BUTTON_RPAR = QtWidgets.QPushButton(self.frame)
        self.BUTTON_RPAR.setGeometry(QtCore.QRect(180, 100, 91, 51))
        self.BUTTON_RPAR.setMinimumSize(QtCore.QSize(91, 51))
        self.BUTTON_RPAR.setMaximumSize(QtCore.QSize(91, 51))
        self.BUTTON_RPAR.setObjectName("BUTTON_RPAR")
        self.BUTTON_DIV = QtWidgets.QPushButton(self.frame)
        self.BUTTON_DIV.setGeometry(QtCore.QRect(270, 100, 91, 51))
        self.BUTTON_DIV.setMinimumSize(QtCore.QSize(91, 51))
        self.BUTTON_DIV.setMaximumSize(QtCore.QSize(91, 51))
        self.BUTTON_DIV.setObjectName("BUTTON_DIV")
        self.BUTTON_NINE = QtWidgets.QPushButton(self.frame)
        self.BUTTON_NINE.setGeometry(QtCore.QRect(0, 100, 91, 51))
        self.BUTTON_NINE.setMinimumSize(QtCore.QSize(91, 51))
        self.BUTTON_NINE.setMaximumSize(QtCore.QSize(91, 51))
        self.BUTTON_NINE.setObjectName("BUTTON_NINE")
        self.BUTTON_LPAR = QtWidgets.QPushButton(self.frame)
        self.BUTTON_LPAR.setGeometry(QtCore.QRect(90, 100, 91, 51))
        self.BUTTON_LPAR.setMinimumSize(QtCore.QSize(91, 51))
        self.BUTTON_LPAR.setMaximumSize(QtCore.QSize(91, 51))
        self.BUTTON_LPAR.setObjectName("BUTTON_LPAR")
        self.BUTTON_C = QtWidgets.QPushButton(self.frame)
        self.BUTTON_C.setGeometry(QtCore.QRect(180, 50, 91, 51))
        self.BUTTON_C.setMinimumSize(QtCore.QSize(91, 51))
        self.BUTTON_C.setMaximumSize(QtCore.QSize(91, 51))
        self.BUTTON_C.setObjectName("BUTTON_C")
        self.BUTTON_B = QtWidgets.QPushButton(self.frame)
        self.BUTTON_B.setGeometry(QtCore.QRect(90, 50, 91, 51))
        self.BUTTON_B.setMinimumSize(QtCore.QSize(91, 51))
        self.BUTTON_B.setMaximumSize(QtCore.QSize(91, 51))
        self.BUTTON_B.setObjectName("BUTTON_B")
        self.BUTTON_BACK = QtWidgets.QPushButton(self.frame)
        self.BUTTON_BACK.setGeometry(QtCore.QRect(270, 50, 91, 51))
        self.BUTTON_BACK.setMinimumSize(QtCore.QSize(91, 51))
        self.BUTTON_BACK.setMaximumSize(QtCore.QSize(91, 51))
        self.BUTTON_BACK.setObjectName("BUTTON_BACK")
        self.BUTTON_A = QtWidgets.QPushButton(self.frame)
        self.BUTTON_A.setGeometry(QtCore.QRect(0, 50, 91, 51))
        self.BUTTON_A.setMinimumSize(QtCore.QSize(91, 51))
        self.BUTTON_A.setMaximumSize(QtCore.QSize(91, 51))
        self.BUTTON_A.setObjectName("BUTTON_A")
        self.EDITOR_LINE = QtWidgets.QLineEdit(self.frame)
        self.EDITOR_LINE.setGeometry(QtCore.QRect(0, 0, 361, 51))
        self.EDITOR_LINE.setMinimumSize(QtCore.QSize(361, 51))
        self.EDITOR_LINE.setMaximumSize(QtCore.QSize(361, 51))
        self.EDITOR_LINE.setObjectName("EDITOR_LINE")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 370, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.BUTTON_ENTER.setText(_translate("MainWindow", "="))
        self.BUTTON_CLEAR.setText(_translate("MainWindow", "CLEAR"))
        self.BUTTON_PERIOD.setText(_translate("MainWindow", "."))
        self.BUTTON_STORE.setText(_translate("MainWindow", "STORE"))
        self.BUTTON_TWO.setText(_translate("MainWindow", "2"))
        self.BUTTON_PLUS.setText(_translate("MainWindow", "+"))
        self.BUTTON_ZERO.setText(_translate("MainWindow", "0"))
        self.BUTTON_ONE.setText(_translate("MainWindow", "1"))
        self.BUTTON_FIVE.setText(_translate("MainWindow", "5"))
        self.BUTTON_MINUS.setText(_translate("MainWindow", "-"))
        self.BUTTON_THREE.setText(_translate("MainWindow", "3"))
        self.BUTTON_FOUR.setText(_translate("MainWindow", "4"))
        self.BUTTON_EIGHT.setText(_translate("MainWindow", "8"))
        self.BUTTON_MULT.setText(_translate("MainWindow", "*"))
        self.BUTTON_SIX.setText(_translate("MainWindow", "6"))
        self.BUTTON_SEVEN.setText(_translate("MainWindow", "7"))
        self.BUTTON_RPAR.setText(_translate("MainWindow", ")"))
        self.BUTTON_DIV.setText(_translate("MainWindow", "DIV"))
        self.BUTTON_NINE.setText(_translate("MainWindow", "9"))
        self.BUTTON_LPAR.setText(_translate("MainWindow", "("))
        self.BUTTON_C.setText(_translate("MainWindow", "C"))
        self.BUTTON_B.setText(_translate("MainWindow", "B"))
        self.BUTTON_BACK.setText(_translate("MainWindow", "BACK"))
        self.BUTTON_A.setText(_translate("MainWindow", "A"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

